server:
  port: 8091
  max-http-header-size: 16KB
  shutdown: graceful
  servlet.encoding:
    charset: UTF-8
    force: true
    enabled: true

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/patient
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.ground: debug
